# Change these first
owner: releen # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: RelEng Concourse
    url: https://releng.ci.cf-app.com
  - name: TR2 Concourse
    url: https://ci.prs.releng.rocks
  - name: Pipestat
    url: https://pipestat.releng.rocks
  - name: Upgrade Planner
    url: https://upgrade-planner.pivotal.io

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.releng.rocks
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Platform Provider Experience Status
  introTitle: "**PPE Status** monitors the health of our tools."
  introMessage: If you want to add a new service to monitor, go to [the repo](https://github.com/releen/upptime/blob/main/.upptimerc.yml) and add a new service.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/releen/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
